export const state_prototype = {
    loggedIn: false,
    name: "",
    surname: "",
    id: "",
    accountType: "",
    HEScode: "",
    groups: [],
    exams: [],
    attendance: [],
    coursesThaught: [],
    courses: [],
    email: "",
    isCovid: false,
    tests: [],
    isolationStartDate: "",
    isoEndDate: "",
    vaccinated: false,
    recovered: false,
    negativeTest: false,
    exams:[],
    isAllowedOnCampus: true,
    weeklyReport: []
}
