export const state_prototype = {
    name: "Mister",
    surname: "NO",
    id: 21901784,
    accountType: "student",
    HEScode: "22EF56",
    groups: [],
    attendance: [],
    courses: [],
    email: "ter_no@gmail.com",
    isCovid: false,
    tests: [],
    isolationStartDate: "",
    isoEndDate: "",
    isoRemainingDays: 0,
    vaccinated: false,
    recovered: false,
    negativeTest: false,
    isAllowedOnCampus: false
}
